config_version = "0"

exclude_patterns = [
  "*_min.*",
  "*-min.*",
  "*.min.*",
  "**/.yarn/**",
  "**/*.d.ts",
  "**/assets/**",
  "**/bower_components/**",
  "**/build/**",
  "**/cache/**",
  "**/config/**",
  "**/db/**",
  "**/deps/**",
  "**/dist/**",
  "**/extern/**",
  "**/external/**",
  "**/generated/**",
  "**/Godeps/**",
  "**/gradlew/**",
  "**/mvnw/**",
  "**/node_modules/**",
  "**/protos/**",
  "**/seed/**",
  "**/target/**",
  "**/templates/**",
  "**/testdata/**",
  "**/vendor/**",
  "**/.devcontainer/**",
  "**/.claude/**",
  ".venv/**",
  "**/.tox/**",
  "misc/",
]

test_patterns = [
  "**/test/**",
  "**/spec/**",
  "**/*.test.*",
  "**/*.spec.*",
  "**/*_test.*",
  "**/*_spec.*",
  "**/test_*.*",
  "**/spec_*.*",
]

[smells]
mode = "monitor"

[[source]]
name = "default"
default = true

[[plugin]]
name = "dockerfmt"

[[plugin]]
name = "hadolint"

[[plugin]]
name = "ripgrep"

[[plugin]]
name = "radarlint-js"

[[plugin]]
name = "prettier"

[[plugin]]
name = "shellcheck"

[[plugin]]
name = "shfmt"

[[plugin]]
name = "yamllint"
